-- MIGRACIÓN: Refactorizar tabla usuario - Eliminar campo redundante 'estado'
-- Mantener únicamente 'activo' como booleano
--
-- ⚠️ Si la tabla ya tiene la estructura nueva (sin columna 'estado'),
--    la migración se salta automáticamente.
--
-- ATENCIÓN: Tablas con PK de usuario (como auth_attempts si la hubiera)
--           se respetan porque la migración no usa CASCADE.

DO $$
DECLARE
    v_has_estado BOOLEAN;
BEGIN
    -- Verificar si la tabla usuario tiene la columna 'estado' (estructura antigua)
    SELECT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'usuario'
          AND column_name = 'estado'
    ) INTO v_has_estado;

    IF NOT v_has_estado THEN
        RAISE NOTICE 'La tabla usuario ya tiene la estructura nueva. Saltando migración.';
        RETURN;
    END IF;

    -- Paso 1: Crear tabla temporal con estructura refactorizada
    CREATE TABLE usuario_new (
        id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_completo VARCHAR(255) NOT NULL,
        correo VARCHAR(255) NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL,
        rol VARCHAR(50) NOT NULL DEFAULT 'REGISTRADOR_DONACIONES',
        activo BOOLEAN NOT NULL DEFAULT TRUE,
        fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

        CHECK (rol IN ('ADMIN', 'CENSADOR', 'OPERADOR_ENTREGAS', 'COORDINADOR_LOGISTICA', 'FUNCIONARIO_CONTROL', 'REGISTRADOR_DONACIONES'))
    );

    -- Paso 2: Copiar datos existentes y convertir 'estado' a 'activo'
    INSERT INTO usuario_new (id_usuario, nombre_completo, correo, password_hash, rol, activo, fecha_creacion, fecha_actualizacion)
    SELECT
        id_usuario,
        nombre_completo,
        correo,
        password_hash,
        rol,
        CASE
            WHEN estado = 'ACTIVO' OR estado IS NULL THEN TRUE
            WHEN estado = 'INACTIVO' THEN FALSE
            ELSE activo
        END,
        fecha_creacion,
        fecha_actualizacion
    FROM usuario;

    -- Paso 3: Intercambiar nombres de tablas
    ALTER TABLE usuario RENAME TO usuario_backup;
    ALTER TABLE usuario_new RENAME TO usuario;
    DROP TABLE usuario_backup;

    -- Paso 4: Ajustar la secuencia al máximo ID migrado
    PERFORM setval(
        'usuario_id_usuario_seq',
        (SELECT MAX(id_usuario) FROM usuario),
        true
    );
END
$$;

-- Paso 5: Recrear índices (seguro ejecutar siempre; no falla si ya existen)
CREATE INDEX IF NOT EXISTS idx_usuario_correo ON usuario(correo);
CREATE INDEX IF NOT EXISTS idx_usuario_activo ON usuario(activo);
CREATE INDEX IF NOT EXISTS idx_usuario_rol ON usuario(rol);
