-- MIGRACIÓN: Refactorizar tabla usuario - Eliminar campo redundante 'estado'
-- Mantener únicamente 'activo' como booleano
-- Ejecutar este script si la tabla usuario existe con campos redundantes
--
-- ⚠️ SOLUCIÓN APLICADA: GENERATED BY DEFAULT AS IDENTITY
-- Permite insertar valores explícitos durante la migración mientras mantiene autoincrement
-- La secuencia se ajusta automáticamente al máximo ID migrado al final

BEGIN TRANSACTION;

-- Paso 1: Crear tabla temporal con estructura refactorizada
-- GENERATED BY DEFAULT AS IDENTITY permite sobrescribir con valores explícitos (necesario para migración)
-- mientras mantiene la capacidad de autoincrement para nuevos registros
CREATE TABLE usuario_new (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(255) NOT NULL,
    correo VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(50) NOT NULL DEFAULT 'REGISTRADOR_DONACIONES',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (rol IN ('ADMIN', 'CENSADOR', 'OPERADOR_ENTREGAS', 'COORDINADOR_LOGISTICA', 'FUNCIONARIO_CONTROL', 'REGISTRADOR_DONACIONES'))
);

-- Paso 2: Copiar datos existentes y convertir 'estado' a 'activo'
-- Se insertan los id_usuario originales para mantener integridad referencial
INSERT INTO usuario_new (id_usuario, nombre_completo, correo, password_hash, rol, activo, fecha_creacion, fecha_actualizacion)
SELECT
    id_usuario,
    nombre_completo,
    correo,
    password_hash,
    rol,
    CASE
        WHEN estado = 'ACTIVO' OR estado IS NULL THEN TRUE
        WHEN estado = 'INACTIVO' THEN FALSE
        ELSE activo
    END as activo,
    fecha_creacion,
    fecha_actualizacion
FROM usuario;

-- Paso 3: Eliminar tabla anterior y renombrar nueva (FORMA SEGURA - SIN CASCADE)
-- ⚠️ ¿POR QUÉ NO USAR CASCADE?
-- DROP TABLE usuario CASCADE puede eliminar automáticamente:
--   - Vistas que dependan de usuario
--   - Triggers asociados
--   - Constraints en otras tablas
--   - Otros objetos dependientes
-- Sin recrearlos, causando pérdida de funcionalidad.
--
-- SOLUCIÓN SEGURA: Método de intercambio de nombres
-- 1. Renombra la tabla antigua a nombre temporal
-- 2. Renombra la nueva tabla al nombre original
-- 3. Elimina el backup temporal (sin CASCADE si no hay dependencias)

-- Paso 3a: Renombrar tabla antigua a backup
ALTER TABLE usuario RENAME TO usuario_backup;

-- Paso 3b: Renombrar tabla nueva al nombre original
ALTER TABLE usuario_new RENAME TO usuario;

-- Paso 3c: Eliminar tabla de backup SIN CASCADE (si no hay dependencias, funcionará)
-- Si esta línea falla, significa que hay dependencias que deben ser revisadas
DROP TABLE usuario_backup;

-- Paso 4: Ajustar la secuencia al máximo ID migrado
-- Esto asegura que los próximos IDs generados automáticamente no entren en conflicto
SELECT setval(
    'usuario_id_usuario_seq',
    (SELECT MAX(id_usuario) FROM usuario),
    true
);

-- Paso 5: Recrear índices
CREATE INDEX idx_usuario_correo ON usuario(correo);
CREATE INDEX idx_usuario_activo ON usuario(activo);
CREATE INDEX idx_usuario_rol ON usuario(rol);

COMMIT;

-- ✅ VERIFICACIÓN
SELECT
    COUNT(*) as total_usuarios,
    COUNT(CASE WHEN activo THEN 1 END) as usuarios_activos,
    COUNT(CASE WHEN NOT activo THEN 1 END) as usuarios_inactivos,
    MAX(id_usuario) as max_id_migrado
FROM usuario;

-- Verificar que la secuencia está correctamente ajustada
SELECT last_value FROM usuario_id_usuario_seq;
