-- ========================================================================
-- SCRIPT DE VALIDACIÓN DE MIGRACIÓN - usuario_hu01_hu02
-- ========================================================================
-- Este script valida que la migración se ejecutó correctamente
-- sin pérdida de datos y con todas las restricciones intactas
-- ========================================================================

\echo '============================================'
\echo 'VALIDACIÓN DE MIGRACIÓN DE TABLA USUARIO'
\echo '============================================'
\echo ''

-- 1. Verificar estructura de la tabla
\echo '1️⃣  Verificando estructura de la tabla usuario...'
\d usuario
\echo ''

-- 2. Verificar cantidad de registros migrados
\echo '2️⃣  Verificando cantidad de registros migrados...'
SELECT 
    COUNT(*) as total_usuarios,
    COUNT(CASE WHEN activo THEN 1 END) as usuarios_activos,
    COUNT(CASE WHEN NOT activo THEN 1 END) as usuarios_inactivos,
    MAX(id_usuario) as max_id_migrado,
    MIN(id_usuario) as min_id_migrado
FROM usuario;
\echo ''

-- 3. Verificar que no hay campos 'estado' (debe estar eliminado)
\echo '3️⃣  Verificando que el campo "estado" fue eliminado...'
SELECT 
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name='usuario' AND column_name='estado'
        ) THEN '❌ FALLO: Campo "estado" aún existe'
        ELSE '✅ OK: Campo "estado" eliminado correctamente'
    END as validacion;
\echo ''

-- 4. Verificar que el campo 'activo' existe
\echo '4️⃣  Verificando que el campo "activo" existe...'
SELECT 
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'usuario' AND column_name = 'activo';
\echo ''

-- 5. Verificar identidad generada
\echo '5️⃣  Verificando GENERATED BY DEFAULT AS IDENTITY...'
SELECT 
    column_name,
    is_identity,
    identity_generation,
    identity_start,
    identity_increment
FROM information_schema.columns
WHERE table_name = 'usuario' AND is_identity = 'YES';
\echo ''

-- 6. Verificar secuencia ajustada
\echo '6️⃣  Verificando que la secuencia está correctamente ajustada...'
SELECT 
    sequence_name,
    last_value,
    (SELECT MAX(id_usuario) FROM usuario) as max_id_actual,
    CASE 
        WHEN last_value >= (SELECT MAX(id_usuario) FROM usuario) THEN '✅ OK: Secuencia ajustada correctamente'
        ELSE '⚠️  ADVERTENCIA: Secuencia podría estar baja'
    END as estado_secuencia
FROM usuario_id_usuario_seq;
\echo ''

-- 7. Verificar que todos los registros tienen datos válidos
\echo '7️⃣  Verificando integridad de datos...'
SELECT 
    COUNT(*) as total_registros,
    COUNT(CASE WHEN nombre_completo IS NOT NULL THEN 1 END) as con_nombre,
    COUNT(CASE WHEN correo IS NOT NULL THEN 1 END) as con_correo,
    COUNT(CASE WHEN password_hash IS NOT NULL THEN 1 END) as con_password,
    COUNT(CASE WHEN rol IS NOT NULL THEN 1 END) as con_rol,
    COUNT(CASE WHEN activo IS NOT NULL THEN 1 END) as con_activo
FROM usuario;
\echo ''

-- 8. Listar todos los usuarios migrados
\echo '8️⃣  Lista de usuarios migrados:'
SELECT 
    id_usuario,
    nombre_completo,
    correo,
    rol,
    CASE WHEN activo THEN 'ACTIVO' ELSE 'INACTIVO' END as estado,
    fecha_creacion
FROM usuario
ORDER BY id_usuario;
\echo ''

-- 9. Verificar índices creados
\echo '9️⃣  Verificando índices creados:'
SELECT 
    indexname,
    tablename,
    indexdef
FROM pg_indexes
WHERE tablename = 'usuario'
ORDER BY indexname;
\echo ''

-- 10. Resumen final
\echo '🔟 RESUMEN FINAL:'
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN '✅ Migración EXITOSA - Datos presentes'
        ELSE '❌ Migración FALLIDA - Sin datos'
    END as resultado_migración,
    COUNT(*) as total_usuarios_validados
FROM usuario;
\echo ''
\echo '============================================'
\echo 'FIN DE VALIDACIÓN'
\echo '============================================'
