from enum import Enum


class UserRole(str, Enum):
    """Roles permitidos en el sistema SGAH"""
    ADMIN = "ADMIN"
    CENSADOR = "CENSADOR"
    OPERADOR_ENTREGAS = "OPERADOR_ENTREGAS"
    COORDINADOR_LOGISTICA = "COORDINADOR_LOGISTICA"
    FUNCIONARIO_CONTROL = "FUNCIONARIO_CONTROL"
    REGISTRADOR_DONACIONES = "REGISTRADOR_DONACIONES"
